### ISSUE TITLE
Если у нас не получилось распарсить запрос, предлагаю вернуть BadRequest (400).

### ISSUE THREAD

**Issue by alexalok** [kingkej/ReceiptVerifierMiddlewareEndpoint#2]
https://github.com/kingkej/ReceiptVerifierMiddlewareEndpoint/blob/2ed6f2bc0cbb06d317f1df0c2ee81e0b521d895f/ReceiptVerifierEndpoint/Middlewares/ReceiptVerifierEndpointMiddleware.cs#L29-L32

**Comment by kingkej** [comment]
Resolved
